# Generated by Django 3.1.4 on 2021-01-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('In Production', 'In Production'), ('Shipping', 'Shipping'), ('Delivered', 'Delivered')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Pah-Tempe', 'Pah-Tempe'), ('Feather', 'Feather'), ('Keota', 'Keota'), ('Uinta', 'Uinta'), ('Wokova', 'Wokaova'), ('Saffron', 'Saffron'), ('Primrose', 'Primrose'), ('Forager', 'Forager'), ('Terra Vida', 'Terra Vida'), ('Childrens', 'Childrens')], max_length=200, null=True)),
                ('price', models.FloatField(null=True)),
                ('category', models.CharField(choices=[('Sandal', 'Sandal'), ('Close-Toed Shoe', 'Close-Toed Shoe')], max_length=200, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
