# Generated by Django 3.1.4 on 2021-01-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210118_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
