# Generated by Django 3.1.4 on 2021-03-01 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20210226_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='theme',
            field=models.CharField(choices=[('Light', 'Light'), ('Dark', 'Dark')], default='Dark', max_length=200, null=True),
        ),
    ]
